### ISSUE TITLE
Sysrc and OID style names

### ISSUE THREAD

**Issue by creaky** [dlundgren/ansible-freebsd-modules#17]
Hi,
The inability to utilise OID style names is an issue when using sysrc to update /boot/loader.conf. Such names are often used, as an example net.pf.source_nodes_hashsize.

Additionally, there appears to be no documentation stating this limitation.

In source, https://github.com/dlundgren/ansible-freebsd-modules/blob/master/library/sysrc at line 237 was the only clue as to why the error message "Name may only contain alpha-numeric and underscore characters" happens.

What is preventing OID style names from being supported? Could the documentation be updated to reflect this limitation until OID style names support is enabled.

**Comment by dlundgren** [comment]
Thanks for letting me know about the documentation limitation! I got that updated.

That being said, the `sysrc` program no longer supports OID style names. Please see https://github.com/dlundgren/ansible-freebsd-modules/issues/11 for the discussion about why this module doesn't allow OID style names.

**Comment by bsdlme** [comment]
sysrc's author once told me that sysrc is not desigend to be used with other files than rc.conf and those in rc.conf.d/ because they use shell script syntax while loader.conf and sysctl.conf do not.
