### ISSUE TITLE
Convert this to a collection

### ISSUE THREAD

**Issue by dlundgren** [dlundgren/ansible-freebsd-modules#18]
Converting this to a collection would make it easier to use until the modules are pulled in to a community collection.

**Comment by eengstrom** [comment]
Before I dive in and even think about contributing to this issue, anyone else actively working on it?

**Comment by dlundgren** [comment]
I am not working towards this at the moment. My plan is to start working towards getting `kld` in to community.general.

**Comment by eengstrom** [comment]
Thanks - I mostly need `sysrc` at the moment.  Will probably fork.  

re: `community.general`, LMK if you want help with the same thing for `sysrc`, though I note that you've already started that from the comments in #12 - thanks.

**Comment by dlundgren** [comment]
`sysrc` is likely going to be in the next release of `community.general`, which is due this month. So I'm looking forward to deleting all the copy/paste versions of sysrc I have lying around.

**Comment by hhartzer** [comment]
Can this be closed out now? Might be worth updating the readme to let people know to use community.general.sysrc.

**Comment by dlundgren** [comment]
`sysrc` has been moved to the `community.general` collection. `kld` will be following.
