### ISSUE TITLE
kld: Failure to detect already-loaded modules

### ISSUE THREAD

**Issue by 2bithacker** [dlundgren/ansible-freebsd-modules#6]
I tried using the `kld` module today to install the `aesni` module. It load the module fine, but on subsequent runs it doesn't detect the module as installed and so loads it again, reporting changed on every run.

It looks like using `kldstat -m` to detect loaded modules isn't always accurate, as the module name doesn't match modname. In this case `aesni.ko` loads a modname called `nexus/aesni`.

```
$ kldstat | grep aesni
 4    1 0xffffffff8248d000 bd50     aesni.ko

$ kldstat -m aesni
kldstat: can't find module aesni: No such file or directory

$ kldstat -v | grep -C 1 aesni
                 1 opensolaris
 4    1 0xffffffff8248d000 bd50     aesni.ko (/boot/kernel/aesni.ko)
        Contains modules:
                Id Name
                 6 nexus/aesni
 5    1 0xffffffff82499000 84b0     cryptodev.ko (/boot/kernel/cryptodev.ko)
```

**Comment by dlundgren** [comment]
I switched the usage of `kldstat` from `kldstat -m <name>` to `kldstat -n <name>.ko`. This works to check for the module. I was able to load/unload the aesni module this way, along with other modules.

**Comment by 2bithacker** [comment]
Cool, thanks!
